### ISSUE TITLE
"Add new job" should clear "company" and "position" fields when canceling/saving

### ISSUE THREAD

**Issue by hanseulshim** [danny-shi/jobseek#1]
1. Click "ADD NEW JOB"
2. Fill in company and position fields
3. Click "Save" or "Cancel"

Expected behavior: fields should be cleared when opening the same popup

![image](https://user-images.githubusercontent.com/5977102/92966949-6e155000-f446-11ea-8c2f-80ba615a37ae.png)

**Comment by danny-shi** [comment]
Should be fixed now!
